#! /bin/sh
#

kernel_version=`uname -r`
lib_path="/lib/modules/$kernel_version/kernel/drivers/amlogic/wifi"

case "$1" in
  start)
        echo "Starting wifi..."
   		/sbin/insmod $lib_path/broadcm_40181/dhd.ko "firmware_path=/etc/wifi/40183/fw_bcm40183b2.bin nvram_path=/etc/wifi/40183/nvram.txt" 
    ;;
  stop)
        echo "Stopping wifi..."
   		/sbin/modprobe -r dhd
    ;;
  restart|reload)
        echo "Restarting wifi..."
   		/sbin/modprobe -r dhd
   		/sbin/insmod $lib_path/broadcm_40181/dhd.ko "firmware_path=/etc/wifi/40183/fw_bcm40183b2.bin nvram_path=/etc/wifi/40183/nvram.txt" 
    ;;
  *)
    ;;
esac

exit $?
